name: SAC
main: DarkWav\SAC\SAC
version: 3.1.1
load: STARTUP
enable: STARTUP
author: Infernus101
api: [2.0.0,1.0.0]
commands:
      shadowanticheat:
           description: Shows ShadowAntiCheat version
           aliases: ["ShadowAntiCheat","AntiCheat","SAC"]
      sac:
           description: Shows ShadowAntiCheat version
           aliases: ["ShadowAntiCheat","AntiCheat","SAC"]
permissions:
    legitop:
        description: "A permission."
        default: false
    sac:
        description: "Allows to use all sac features."
        default: false
        children:
            sac.admin:
                description: "Get notified when someone is hacking."
                default: op
            sac.fly:
                description: "A permission."
                default: false
            sac.glide:
                description: "A permission."
                default: false
            sac.speed:
                description: "A permission."
                default: false
            sac.noclip:
                description: "A permission."
                default: false
            sac.reach:
                description: "A permission."
                default: false
            sac.instantkill:
                description: "A permission."
                default: false
            sac.killaura:
                description: "A permission."
                default: false
            sac.regen:
                description: "A permission."
                default: false
            sac.forcegamemode:
                description: "A permission."
                default: false

