name: WatchDog
main: DarkWav\WatchDog\WatchDog
version: 3.2.5
load: STARTUP
enable: STARTUP
author: DarkWav
api: [3.0.0-ALPHA1,3.0.0-ALPHA2,3.0.0-ALPHA3,3.0.0-ALPHA4,3.0.0-ALPHA5,3.0.0-ALPHA6,3.0.0-ALPHA7,3.0.0-ALPHA8,3.0.0-ALPHA9,3.0.0-ALPHA10,3.0.0]
commands:
      watchdog:
           description: Shows WatchDog version
           aliases: ["WatchDog","AntiCheat","WD"]
      wd:
           description: Shows ShadowAntiCheat version
           aliases: ["ShadowAntiCheat","AntiCheat","SAC"]
permissions:
    legitop:
        description: "A permission."
        default: false
    sac:
        description: "Allows to use all sac features."
        default: false
        children:
            wd.admin:
                description: "Get notified when someone is hacking."
                default: op
            wd.fly:
                description: "A permission."
                default: false
            wd.glide:
                description: "A permission."
                default: false
            wd.speed:
                description: "A permission."
                default: false
            wd.noclip:
                description: "A permission."
                default: false
            wd.reach:
                description: "A permission."
                default: false
            wd.instantkill:
                description: "A permission."
                default: false
            wd.killaura:
                description: "A permission."
                default: false
            wd.regen:
                description: "A permission."
                default: false
            wd.forcegamemode:
                description: "A permission."
                default: false

