name: SAC
main: DarkWav\SAC\SAC
version: 3.6.0
load: STARTUP
enable: STARTUP
author: DarkWav
api: [3.0.0,4.0.0]
commands:
      shadowanticheat:
           description: Shows ShadowAntiCheat version
           aliases: ["ShadowAntiCheat","AntiCheat","SAC"]
      sac:
           description: Shows ShadowAntiCheat version
           aliases: ["ShadowAntiCheat","AntiCheat","SAC"]
permissions:
    sac:
        description: "Allows to use all SAC features."
        default: false
        children:
            sac.admin:
                description: "Get notified when someone is hacking."
                default: op
            sac.fly:
                description: "A permission."
                default: false
            sac.glide:
                description: "A permission."
                default: false
            sac.speed:
                description: "A permission."
                default: false
            sac.noclip:
                description: "A permission."
                default: false
            sac.reach:
                description: "A permission."
                default: false
            sac.killaura:
                description: "A permission."
                default: false
            sac.regen:
                description: "A permission."
                default: false
#//////////////////////////////////////////////////////
#//                                                  //
#//     SAC by DarkWav.                              //
#//     Distributed under the GGPL License.          //
#//     Copyright (C) 2018 DarkWav                   //
#//                                                  //
#//////////////////////////////////////////////////////
